project_id = "seearalooznyeqkbtgwv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
verify_jwt = false
slug = "generate-pdf"
name = "generate-pdf"