// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seearalooznyeqkbtgwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlZWFyYWxvb3pueWVxa2J0Z3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4ODA1NTgsImV4cCI6MjA1MjQ1NjU1OH0.cy3K9Gb1T80cTcXlqdfVEtKNQ6kJ5a1tza3BtNxS6QY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);